version: '3.8'

services:
  db:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demoproject
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  django_backend:
    build:
      context: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  nextjs_frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - django_backend

volumes:
  db_data:
